version: "3.8"
services:
  server:
    build:
      context: ./
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    env_file: ./.env
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/recipedb?allowPublicKeyRetrieval=true&useSSL=false
    networks:
      - springmysql-net
    depends_on:
      mysqldb:
        condition: service_healthy

  mysqldb:
    image: mysql:5.7
    networks:
      - springmysql-net
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=recipedb
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

networks:
  springmysql-net: